### ISSUE TITLE
CI/CD attach `.xar` release assets to github

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/fusion-studio-api#52]
and / or automate the upload to `https://www.fusiondb.com/download/`

**Comment by adamretter** [comment]
I don't want to automate this via CI at this time. The release process for our products is complex and spans much more than a singular repos CI.

**Comment by duncdrum** [comment]
and thats precisely why i want to automate this. How is doing this manually, and then having hardcoded URLs elsewhere to an endpoint that is undocumented, we need another set of  access credentials for, actually decreasing complexity or increasing productivity?  
how does it help our complex release process to have to manually look up the latest release version and then search and replace xar names by hand?

**Comment by duncdrum** [comment]
@adamretter are xars now automatically uploaded to FusionDB.com? otherwise i can you reopen this issue until we have an automatic upload from which CI can get the latest version of the API / FusionDB is certain to get the latest version during builds

**Comment by adamretter** [comment]
Xars are not yet automatically uploaded. We need to implement this for when `mvn release:perform` is run, however I don't want to do releases from CI yet. So maybe we need a separate issue?
